### ISSUE TITLE
Реализация выделения линий контура загруженной модели в MeshGeneratorControl проект ModelModule

### ISSUE THREAD

**Issue by ONEGOCH** [ONEGOCH/BazisCAE.GUI#11]
Привет. Теперь нужно доделать выделение контура при выборе объекта в дереве (TreeView). Как технически это сделать мы примерно на этой неделе разобрали. Я писать в подробностях не буду.

**Comment by ONEGOCH** [comment]
Работать в ветке которая содержит твое имя и описание задачи

**Comment by ONEGOCH** [comment]
Привет. В каком классе идёт ссылка на сборку workingweek?

**Comment by knsplm** [comment]
Гоша, привет, WorkingWeek в зависимостях TaskModule. Я залился в ветку, которую ты создал под задачу ;) Выделение работает. При выборе следующей кривой из TreeView получается, что предыдущая выбранная кривая продолжает быть выделенной, так и должно быть ? Можно сделать так, чтобы предыдущая кривая меняла цвет в дефолтный. То есть на сцене будет только одна выбранная кривая, если например нужно сделать множественный выбор кривых можно учитывать нажатие клавиши shift. Как тебе такая идея ?
![select](https://github.com/ONEGOCH/BazisGUI4.1/assets/131250422/0c05e999-b080-458c-bcc9-26529de3cca6)

**Comment by ONEGOCH** [comment]
> Гоша, привет, WorkingWeek в зависимостях TaskModule. Я залился в ветку, которую ты создал под задачу ;) Выделение работает. При выборе следующей кривой из TreeView получается, что предыдущая выбранная кривая продолжает быть выделенной, так и должно быть ? Можно сделать так, чтобы предыдущая кривая меняла цвет в дефолтный. То есть на сцене будет только одна выбранная кривая, если например нужно сделать множественный выбор кривых можно учитывать нажатие клавиши shift. Как тебе такая идея ? ![select](https://private-user-images.githubusercontent.com/131250422/280928918-0c05e999-b080-458c-bcc9-26529de3cca6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTkzNTEwNDksIm5iZiI6MTY5OTM1MDc0OSwicGF0aCI6Ii8xMzEyNTA0MjIvMjgwOTI4OTE4LTBjMDVlOTk5LWIwODAtNDU4Yy1iY2M5LTI2NTI5ZGUzY2NhNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEwN1QwOTUyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzgxZWMwODUzY2U0NDg1ZGEzZmZkNjBmNmZiYmE1OTdmOTUyYTNlM2UwMjlhYWUxYTIwNDE1ZDk2NjkxY2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XenIu1JZQOyhLDtQO4B55053YF5p9YpvPJZsZ3z5u_0)

Привет. Да мне нравиться идея. А выбранной должна быть только одна кривая. Но я подправил, чтобы это было так. Эту задачу я закрываю.
