### ISSUE TITLE
Сделать краткую инструкцию по использованию генератора сетки

### ISSUE THREAD

**Issue by ONEGOCH** [ONEGOCH/BazisCAE.GUI#12]
Николай привет. Требуется краткая инструкция как работать с генератором. Начиная с загрузки CAD и генерации сеток различной плотности. В инструкции нужно описать интерфейс (кнопки). Не обязательно подробно. Можно только самое главное. По возможности с рисунками. Лучше сделать на примере цилиндра или гайки.
Это надо сделать к четвергу этой недели (к обеду). Управишься?

**Comment by knsplm** [comment]
Ок, весь ModelModule описывать ? Или только MeshGeneratorControl ? В Word-e ?

**Comment by ONEGOCH** [comment]
> Ок, весь ModelModule описывать ? Или только MeshGeneratorControl ? В Word-e ?

Только  MeshGeneratorControl. Да world подойдёт.
