### ISSUE TITLE
Доработать логику и графику контрола HeatControl

### ISSUE THREAD

**Issue by ONEGOCH** [ONEGOCH/BazisCAE.GUI#13]
Доработать HeatControl в проекте TaskModule\HeatTreatmentModule\HeatControl.cs

Изменить метод string AddRowInfo()

**Comment by SherhUNV** [comment]
Написал подсчет коэффициента при лучевом и конвекционном воздействии. Сделал базовую проверку.

Также настроил кнопки так, чтобы одна выключала другую и делала поля другой кнопки недоступными для ввода.

**Comment by ONEGOCH** [comment]
Порядок формирования строки данных для heatControl
            
            dataList.Add(cmbProcKinds.Text);
            dataList.Add(cmbEl.Text);
            dataList.Add(**cmbExchFunc.Text**); - это вычисляемый параметр в случае с разделением теплообмена
            dataList.Add(cmbTempFunc.Text);
            dataList.Add(txbStartTime.Text);
            dataList.Add(txbStopTime.Text);
            dataList.Add("*");
