### ISSUE TITLE
Добавить удаление tsf файлов из под GUI (планировщик)

### ISSUE THREAD

**Issue by ONEGOCH** [ONEGOCH/BazisCAE.GUI#21]
Привет нужно реализовать удаление всех tsf файлов из списка на диске при нажатии на кнопку "удалить все" (красный крестик)
Контрол находится тут BazisGUI\TaskModule\BasicAdvisorControls\TaskPlannerControls\TaskPlannerControl1.5.310.cs

**Comment by SherhUNV** [comment]
Добавил удаление файлов с диска по пути проекта через свойство Path

**Comment by ONEGOCH** [comment]
Еще добавить удаление отдельного выделенного tsf файла. Ветка 22...
