### ISSUE TITLE
Внедрить разложение вектора по базису

### ISSUE THREAD

**Issue by ONEGOCH** [ONEGOCH/BazisCAE.GUI#33]
async void TaskAdvisor_AddDataEvent(object arg1, AddDataEventArgs arg2) в TaskModule\TaskPage.cs

**Comment by ONEGOCH** [comment]
Не забудь проверить checkBox в модуле нагрузки и закрепления. Должны отжиматься если выбрано произвольное направление

**Comment by SherhUNV** [comment]
> TaskAdvisor_AddDataEvent

Добавил проверку при нажатии на refresh.
