### ISSUE TITLE
Доделать интерфейс сеточного генератора

### ISSUE THREAD

**Issue by ONEGOCH** [ONEGOCH/BazisCAE.GUI#52]
Привет. Есть несколько вопросов:

**Что делают эти методы? Такое ощущение что оба задают разметку?**
controller.gmshModelSetAttribute($"transfinite {tag}", attributes, (IntPtr)3, ref ierr);
controller.gmshModelMeshSetTransfiniteCurve(tag, nPoints, attributes[1], coef, ref ierr);

Нужно реализовать метод  void ShowCurvesInfo(). Я думаю что он должен перебирать все кривые и брать от них разметку (кол-во точек и алгоритм разбиения). Но может быть у тебя есть еще идеи.

Вот этот метод ооочень странный. Для того, чтобы узнать какая радио кнопка включена не нужно ее создавать. Это надо переписать 100%
       private RadioButton GetSelectedRadioButton(string law)
       {
           var radio = new RadioButton[] { rbtnProgressive, rbtnBump, rbtnBeta };
           for (var i = 0; i < radio.Length; ++i)
               if (radio[i].Text.Contains(law))
                   return radio[i];
           return radio[0];
       }

**Comment by knsplm** [comment]
По порядку:
1) controller.gmshModelSetAttribute - это внутренний метод gmsh позволяет запомнить любые произвольные данные внутрь gmsh, работает примерно как словарь C#, ключ - строка, значение массив строк...
2) controller.gmshModelMeshSetTransfiniteCurve - это и есть метод в который мы передаем параметры трансфиниции кривой, полагаю что он должен вызываться только при нажатии кнопки OK.
3) В GetSelectedRadioButton мы ничего не создаем, мы перебираем ссылки, чтобы узнать какому RadioButton принадлежит аргумент law, для того чтобы его восстанновить в сотояние true - это используется при переключении кривых. Я могу поправить его ничего не создавая, через if else...
