### ISSUE TITLE
Исправить добавление закреплений и нагрузок если выбраны несколько направлений и если выбрано произвольное направление

### ISSUE THREAD

**Issue by ONEGOCH** [ONEGOCH/BazisCAE.GUI#65]
Привет суть такая. Должно быть по каждому закреплению своя строчка. Например если по х и у, то это две строки. Если xyz то это три строки.

**Comment by ONEGOCH** [comment]
Привет. Забыл сказать, что нужно деактивировать произвольное направление в закреплениях, в случае если выбрано "Жесткое"

**Comment by SherhUNV** [comment]
> Привет суть такая. Должно быть по каждому закреплению своя строчка. Например если по х и у, то это две строки. Если xyz то это три строки.

Сделано

**Comment by SherhUNV** [comment]
> Привет. Забыл сказать, что нужно деактивировать произвольное направление в закреплениях, в случае если выбрано "Жесткое"

Если будет выпадать сообщение, что нельзя задать произвольное направление при жестком виде закрепления, будет нормально?
